server:
  port: 8080

spring:
  db:
    username: root
    password: 1234
    database: epiceats
  security:
    user:
      name: user
      password: "$2a$10$s04/G4rv/wGPZDOKELQRAuIC4ayt286sQ7TWnEpLtVqsLGmDmC.ES"
  mail:
    host: smtp.gmail.com
    port: 587
    username: shansathish38@gmail.com
    password: swqgwfeqmxcodkuw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  from: shansathish38@gmail.com
